"""initial migration

Revision ID: 5e91bb3ad97b
Revises: None
Create Date: 2016-08-15 13:37:19.729170

"""

# revision identifiers, used by Alembic.
revision = '5e91bb3ad97b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('snap_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=16), nullable=True),
    sa.Column('regex', sa.String(length=160), nullable=False),
    sa.Column('base', sa.Float(), nullable=False),
    sa.Column('per_ft_adder', sa.Float(), nullable=False),
    sa.Column('rev_level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('pn_format', sa.String(length=64), nullable=False),
    sa.Column('regex', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('rev_level', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_customer_id'), 'series', ['customer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=10), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=True),
    sa.Column('ship_to', sa.String(length=64), nullable=True),
    sa.Column('planner', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('sumbitter', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sumbitter'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_pos_customer_id'), 'pos', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pos_sumbitter'), 'pos', ['sumbitter'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_serie_id'), 'prices', ['serie_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('ln', sa.Integer(), nullable=True),
    sa.Column('pn', sa.String(length=32), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('req_rev_level', sa.String(length=2), nullable=True),
    sa.Column('req_ship_date', sa.DateTime(), nullable=False),
    sa.Column('req_qty', sa.Integer(), nullable=True),
    sa.Column('req_unit_price', sa.Float(), nullable=True),
    sa.Column('upc', sa.String(length=11), nullable=True),
    sa.Column('our_ship_date', sa.DateTime(), nullable=True),
    sa.Column('our_rev_level', sa.String(length=2), nullable=True),
    sa.Column('our_unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_lines_serie_id'), 'po_lines', ['serie_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_lines_serie_id'), table_name='po_lines')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_prices_serie_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_pos_sumbitter'), table_name='pos')
    op.drop_index(op.f('ix_pos_customer_id'), table_name='pos')
    op.drop_table('pos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_series_customer_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('snap_pricing')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('customers')
    ### end Alembic commands ###
